---
title: "Bouts de codes pour analyser les données Cartofriches"
output: html_notebook
---

# Installation des packages
```{r}
install.packages("sf")
install.packages("tidyverse")
```


# Import des données

1)  Les données sont présentes dans le dossier "data"

2)  On importe la donnée friches en format gpkg

```{r}
library(sf)
library(dplyr)

# setwd("C/Users/nicolas.pele/Documents/GitHub/DatavizChallenge-ENTPE")
  
DataFriches_surfaces <- st_read("../data/friches/02_preprocessing/friches_surfaces.gpkg")
DataFriches_points <- st_read("../data/friches/02_preprocessing/friches_points.gpkg")
```

3)  On regarde rapidement ce qu'il y a dedans

```{r}
head(DataFriches_surfaces)
summary(DataFriches_surfaces)
```

# Exemples

**EXEMPLE 1 : Group_by**

```{r}
DataGroupby <- DataFriches_points %>% 
  group_by(comm_nom) %>% # choix de la variable d'aggrégation
  summarise(Nombre = n()) # choix des variables à créer 
```

**EXEMPLE 2 : Jointure**
On importe les données contextuelles
```{r}
DataArtificiation <- read.csv2("../outputs/obs_artif_conso_com_2009_2021.csv")

DataZonageInsee <- read.csv2("../outputs/INSEE_commune.csv")

DataAltitude <- st_read("../outputs/friches_altitude.gpkg")  %>% st_set_crs(4326)
DataMairie <- st_read("../outputs/friches_mairie.gpkg") %>% st_set_crs(4326)
DataCLC <- st_read("../outputs/friches_clc.gpkg")  %>% st_set_crs(4326)
DataGTFS <- st_read("../outputs/friches_stops.gpkg")  %>% st_set_crs(4326)
```


On effectue les jointures
```{r}
# Jointure sur les friches
DataJointure1 <- DataFriches_points %>%
  st_join(DataMairie, by = site_pk)

DataJointure1 <- DataFriches_points %>% as.data.frame %>%
  left_join(DataMairie %>% as.data.frame(), by = "site_pk")

# Jointure à la commune
DataJointure2 <- DataFriches_points %>% as.data.frame %>%
  left_join(DataArtificiation %>% as.data.frame, by = c('comm_insee' = 'idcom'))
```

**EXEMPLE 3 : Sunburst**

```{r}
# Import des packages
library(d3r)
library(sunburstR)

# Création du dataframe approprié
DataSunburst <- table(DataFriches_points$source_nom,DataFriches_points$urba_zone_type) %>%
                                as.data.frame %>%
  rename(level1 = Var1,
         level2 = Var2,
         size = Freq)
DataSunburst

# Création du graphique
tree <- d3_nest(DataSunburst, value_cols = "size", root = "Ensemble des friches")
sund2b(data = tree,
         showLabels = T,
                              tooltip = sund2bTooltip(
           html = htmlwidgets::JS("
function(nodedata, size, percent) {
  return '<span style=\"font-weight: bold;\">' + nodedata.name + '</span>'
}
    ")
         ),
      breadcrumbs = sund2bBreadcrumb(
    html = htmlwidgets::JS("
function(nodedata, size, percent) {
  return '<span style=\"font-weight: bold;\">' + nodedata.name + '</span>' + ' ' + size.toLocaleString() + ' friches ' + '(' + Math.trunc(percent.toFixed(2)*100) + '%' + ')'
}
    ")
  )
)
```

**EXEMPLE 4 : Violin **

```{r}
DataViolin <- 
```
