---
title: "Bouts de codes pour analyser les données Cartofriches"
output: html_notebook
---

# Installation des packages
```{r}
install.packages("sf")
install.packages("tidyverse")
```


# Import des données

1)  Les données sont présentes dans le dossier "data"

2)  On importe la donnée friches en format gpkg

```{r}
library(sf)
library(dplyr)

# setwd("C/Users/nicolas.pele/Documents/GitHub/DatavizChallenge-ENTPE")
  
DataFriches_surfaces <- st_read("../data/friches/02_preprocessing/friches_surfaces.gpkg")
DataFriches_points <- st_read("../data/friches/02_preprocessing/friches_points.gpkg")
```

```{r}
f <- DataFriches_points %>% filter(dep == "13")
f$dep
unique(f$dep)
```

Je filtre les friches qui sont dans PACA
```{r}
f <- DataFriches_points %>% filter(dep %in% c("13", "83", "84", "04", "05", "06"))

# équivalent à
f <- DataFriches_points %>% filter(dep == "13" | dep == "83" | dep == "04" | dep == "05" | dep == "06" | dep == "84")
unique(f$dep)
table(f$dep)
```

Statistiques agrégées par commune
```{r}
stats_comm <- DataFriches_points %>% 
  group_by(comm_nom, comm_insee) %>% 
  summarise(n_friches = n())
```

Statistiques agrégées par département
```{r}
stats_dep <- DataFriches_points %>% 
  group_by(dep) %>% 
  summarise(n_friches = n())
```

```{r}
names(stats_dep)
```
Je sélectionne dep et n_friches avec select
```{r}
stats_dep %>% data.frame %>% select(dep, n_friches)
```

```{r}
stats_dep <- stats_dep %>% data.frame %>% select(-geom)
```

```{r}
range(DataFriches_points$site_surface)
```
```{r}
hist(DataFriches_points$site_surface, xlim=c(0, 74136046.39/2))
```
```{r}
quantile(DataFriches_points$site_surface)
```

```{r}
DataFriches_points <- DataFriches_points %>% mutate(petit = DataFriches_points$site_surface < 12637.69)
table(DataFriches_points$petit)
```
```{r}
f_artificialisation <- read.csv2("../outputs/obs_artif_conso_com_2009_2021.csv")
```

```{r}
names(f_artificialisation)
```

```{r}
stats_comm %>% 
  left_join(f_artificialisation, by=c("comm_insee" = "idcom"))
```



